name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{ secrets.USERNAME }}/working-cicd:v1
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.PASSWORD}}
        password: ${{ secrets.USERNAME }}
    - name: Build and push Docker image
      run: docker push ${{ secrets.USERNAME }}/working-cicd:v1

 
